packages:
  - packages/*
  - playground/*

catalog:
  '@types/node': ^25.1.0
  oxfmt: ^0.27.0
  oxlint: ^1.42.0
  oxlint-tsgolint: ^0.11.4
  turbo: ^2.4.4
  typescript: ^5.9.3
  tailwindcss: ^4.1.18
  '@tailwindcss/vite': ^4.1.18
  vite: ^7.3.1
  vitest: ^4.0.18
  daisyui: ^5.5.16
  tsdown: ^0.20.1
