packages:
  - packages/*
  - playground/*

catalog:
  '@tailwindcss/vite': ^4.1.18
  '@types/node': ^25.1.0
  daisyui: ^5.5.16
  oxfmt: ^0.27.0
  oxlint: ^1.42.0
  oxlint-tsgolint: ^0.11.4
  tailwindcss: ^4.1.18
  tsdown: ^0.20.1
  turbo: ^2.4.4
  typescript: ^5.9.3
  unplugin-vue: ^7.1.1
  vite: ^7.3.1
  vitest: ^4.0.18
  vue: ^3.5.27
  vue-tsc: ^3.2.4
