packages:
  - packages/*
  - playground/*

catalog:
  '@types/node': ^25.1.0
  oxfmt: ^0.27.0
  oxlint: ^1.42.0
  oxlint-tsgolint: ^0.11.4
  turbo: ^2.4.4
  typescript: ^5.9.3
  vite: ^7.3.1
  vitest: ^4.0.18
